MCKIN-24991 Calculating student responses batch wise for xblock-poll
edx-solutions/edx-platform pull request #2060
Opened 2021-01-04 09:07 UTC by ahmed-zubair12

Calculating student responses batch wise while generating report for xblock-poll

2021-02-10 08:08 UTC, attiyaIshaque commented
@ahmed-zubair12 Can you please add more description why we need this?

2021-02-12 07:17 UTC, ahmed-zubair12 commented
@attiyaIshaque description added.

2021-03-02 14:30 UTC, hasnain-naveed requested changes

2021-03-09 08:14 UTC, hasnain-naveed approved these changes

2021-03-09 08:16 UTC, merged