MEI-15697 Staff tools issue
edx-solutions/edx-platform pull request #2172
Opened 2022-01-26 16:28 UTC by wasifarbisoft

2022-01-26 16:29 UTC, wasifarbisoft commented on lms/djangoapps/instructor_task/models.py
> +    def _get_utf8_encoded_rows(self, rows):
reverted back not need of encoding check

2022-01-27 09:10 UTC, mudassir-hafeez requested changes

2022-01-27 09:10 UTC, mudassir-hafeez commented on lms/djangoapps/instructor_task/models.py
> +        else:
It seems to be redundant code for the export stats feature i.e [ProblemResponses](https://github.com/edx-solutions/edx-platform/blob/release-candidate/lms/djangoapps/instructor_task/tasks_helper/grades.py#L1020-L1023)

2022-01-27 09:13 UTC, mudassir-hafeez commented on lms/djangoapps/instructor_task/models.py
> +        else:
[add_rows](https://github.com/edx-solutions/edx-platform/blob/release-candidate/lms/djangoapps/instructor_task/models.py#L275) method almost doing the same, Please consider it against what you are doing.

2022-01-27 11:46 UTC, closed without merging